language: go

go:
  - 1.6

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

install:
  - go get -t -v ./...

script:
  - make test

after_success:
  - goveralls -coverprofile=coverage.txt -service=travis-ci -repotoken cAB56Ntrsjw4nrsp051VYxGlSCnAmFOVb
